package me.DenBeKKer.ntdLuckyBlock;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map.Entry;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.entity.ArmorStand;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPistonExtendEvent;
import org.bukkit.event.block.BlockPistonRetractEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.player.PlayerArmorStandManipulateEvent;
import org.bukkit.event.player.PlayerInteractEntityEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerPickupItemEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.scheduler.BukkitRunnable;

import me.DenBeKKer.ntdLuckyBlock.LBMain.LuckyBlockType;
import me.DenBeKKer.ntdLuckyBlock.api.LuckyBlockAPI;
import me.DenBeKKer.ntdLuckyBlock.api.LuckyBlockNotLoadedException;
import me.DenBeKKer.ntdLuckyBlock.api.LuckyBlockPlaceEvent;
import me.DenBeKKer.ntdLuckyBlock.loader.ConvertManager;
import me.DenBeKKer.ntdLuckyBlock.sk89q.LBWorldGuard;
import me.DenBeKKer.ntdLuckyBlock.util.Config;
import me.DenBeKKer.ntdLuckyBlock.util.GuiManager;
import me.DenBeKKer.ntdLuckyBlock.util.MessagesManager.Message;

@SuppressWarnings("deprecation")
public class LBHandler implements Listener {
	
	@EventHandler
	public void piston(BlockPistonExtendEvent e) {
		
		if(LBMain.getInstance().pistonFix()) {
			e.getBlocks().forEach(n -> {
				if(LuckyBlockAPI.isLuckyBlock(n)) {
					e.setCancelled(true);
					return;
				}
			});
			
			if(e.getDirection() == BlockFace.UP) {
				if(LuckyBlockAPI.isLuckyBlock(e.getBlock().getLocation().add(0, 2, 0).getBlock())) {
					e.setCancelled(true);
					return;
				}
			}
			
		}
		
	}
	
	@EventHandler
	public void piston(BlockPistonRetractEvent e) {
		
		if(LBMain.getInstance().pistonFix()) {
			e.getBlocks().forEach(n -> {
				if(LuckyBlockAPI.isLuckyBlock(n)) {
					e.setCancelled(true);
					return;
				}
			});
			
		}
		
	}
	
	@EventHandler
	public void claim_drop(PlayerPickupItemEvent e) throws LuckyBlockNotLoadedException {
		
		LuckyBlockType type = LuckyBlockAPI.getLuckyBlock(e.getItem().getItemStack(), false, true);
		if(type != null && type.isLoaded()) {
			
			ItemStack item = type.get().getSkull();
			item.setAmount(e.getItem().getItemStack().getAmount());
			e.getItem().setItemStack(item);
			item.setAmount(1);
			
		}
		
	}
	
	@EventHandler
	public void quit(PlayerQuitEvent e) {
		GuiManager.ramFix(e.getPlayer());
		if(LBMain.getReduced() != null && LBMain.getReduced().contains(e.getPlayer()))
			LBMain.getReduced().remove(e.getPlayer());
	}
	
	@EventHandler
	public void explosion(EntityExplodeEvent e) {
		
		if(LBMain.getInstance().explosionFix())
			new ArrayList<>(e.blockList()).forEach(n -> {
				if(LuckyBlockAPI.isLuckyBlock(n)) {
					e.blockList().remove(n);
				}
			});
		
	}
	
	@EventHandler
	public void join(PlayerJoinEvent e) {
		
		if(e.getPlayer().hasPermission("luckyblock.update") && LBMain.needUpdate() && LBMain.inform()) {
			
			new BukkitRunnable() {

				@Override
				public void run() {
					
					if(e.getPlayer() != null && e.getPlayer().isOnline()) {
						
						LBMain.getInstance().informAboutUpdate(e.getPlayer());
						
					}
					
				}
				
			}.runTaskLaterAsynchronously(LBMain.getInstance(), 40);
			
		}
		if(e.getPlayer().hasPermission("luckyblock.warning-luckyblock-changed") &&
				LBMain.warning_luckyblock_changed()) {
			
			Bukkit.getScheduler().runTaskLaterAsynchronously(LBMain.getInstance(), () -> {
				
				if(e.getPlayer() != null && e.getPlayer().isOnline()) {
					
					e.getPlayer().sendMessage("\u00a7c\u00a7l[WARNING] \u00a77[\u00a7eLuckyBlock\u00a77] \u00a76Due LuckyBlock matching method"
							+ " changing, some luckyblocks (That not been generated by plugin method \u00a7eLuckyBlock#getSkull()\u00a76) may wont"
							+ " work. To fix this issue you must disable config.yml option \u00a7cplace.verify-UUID\u00a76. But it not recommended."
							+ " \u00a77(This message wont appear after server restart or reload and only players with permission \u00a78luckyblock."
							+ "warning-luckyblock-changed\u00a77 see it)");
					e.getPlayer().sendMessage("\u00a7c\u00a7l[!] \u00a7fFor more information visit \u00a7bhttps://clck.ru/XC7L7");
					
				}
				
			}, 50);
			
		}
		if(e.getPlayer().hasPermission("luckyblock.convert")) {
			
			int convert = ConvertManager.getRequests();
			if(convert > 0) {
				
				if(LBMain.isPremium()) {
					e.getPlayer().sendMessage("\u00a77[\u00a7eLuckyBlock\u00a77] \u00a7fNew luckyblock configuration update available! Now " +
							"my plugin can store almost any item from any plugin and you can set drop chances for each lucky entry. You can " +
							"convert \u00a7c" + convert + " \u00a7fentry drops to new JSON store format. \u00a7bPerform - \u00a7l/luckyblock convert");
					e.getPlayer().sendMessage("\u00a74[*] \u00a7cTo prevent loss of configuration in case of error, make backup of some files first");
					for(Entry<Config, Collection<String>> entry : ConvertManager.getRequestMap().entrySet())
						e.getPlayer().sendMessage("\u00a74 - \u00a7c" + entry.getKey().getName()
								+ " \u00a77(Have " + entry.getValue().size() + " unconverted items)");
				} else {
					e.getPlayer().sendMessage("\u00a77[\u00a7eLuckyBlock\u00a77] \u00a7fNew luckyblock configuration update available! Now " +
							"my plugin can store almost any item from any plugin and you can set drop chances for each lucky entry. This " +
							"cool feature available in \u00a7bpremium version\u00a7f! You can convert \u00a7c" + convert + " \u00a7fentry " +
							"drops to new JSON store format. \u00a7bCheck out - https://www.spigotmc.org/resources/94872/");
				}
				
			}
			
		}
		
	}
	
	@EventHandler
	public void place(BlockPlaceEvent e) {
		
		LuckyBlockType type = LuckyBlockAPI.getLuckyBlock(e.getItemInHand(), true, true);
		if(type != null && type.isLoaded()) {
			
			if(e.isCancelled()) return;
			
			LuckyBlockPlaceEvent event = new LuckyBlockPlaceEvent(e.getBlock(), e.getPlayer(), type);
			Bukkit.getPluginManager().callEvent(event);
			if(event.isCancelled()) return;
			
			Bukkit.getScheduler().runTaskLater(LBMain.getInstance(), () -> {
				try {
					type.get().placeBlock(e.getBlock(), true);
				} catch (LuckyBlockNotLoadedException e1) {
					e1.printStackTrace();
				}
			}, 1);
			return;
			
		}
		
	}
	
	@EventHandler
	public void broke(BlockBreakEvent e) throws LuckyBlockNotLoadedException {
		
		if(e.getBlock().getType().name().toUpperCase().contains("STAINED_GLASS") ||
				e.getBlock().getType().name().equalsIgnoreCase("TINTED_GLASS")) {
			
			for(LuckyBlockType type : LuckyBlockType.values()) {
				
					for(Entity en : e.getBlock().getWorld().getNearbyEntities(e.getBlock().getLocation().add(0.5, -1.2, 0.5), 0.1, 0.1, 0.1)) {
						
						if(e.isCancelled()) return;
						if(en.getType() != EntityType.ARMOR_STAND) continue;
						ArmorStand stand = (ArmorStand) en;
						if(stand.getCustomName().equalsIgnoreCase(type.name() + ";" + (int)stand.getLocation().getX()
								+ ";" + (int)stand.getLocation().getY() + ";" + (int)stand.getLocation().getZ())
								&& stand.getLocation().add(0, 1.2, 0).getBlock().equals(e.getBlock())) {
							
							if(LBMain.getIsSk89q() && !LBWorldGuard.canBreak(e.getBlock())) {
								e.setCancelled(true);
								return;
							}
							
							if(LBMain.isBreakPermissions() && !e.getPlayer().hasPermission("luckyblock.break." + type.name().toLowerCase())
									&& !e.getPlayer().hasPermission("luckyblock.break.*")) {
								e.getPlayer().sendMessage(Message.CANT_BREAK_LUCKYBLOCK.getAsString().replace("%lb%",
										type.isLoaded() ? type.get().getCustomName() : type.name()));
								e.setCancelled(true);
								return;
							}
							
							if(type.isLoaded()) {
								e.setDropItems(false);
								if(type.get().tryOpen(e.getBlock(), e.getPlayer(), false))
									stand.remove();
								else e.setCancelled(true);
							} else stand.remove();
							return;
							
						}
						
					}
				
			}
			
		}
		
	}
	
	@EventHandler
	public void entity(PlayerArmorStandManipulateEvent e) throws LuckyBlockNotLoadedException {
		
		if(e.getRightClicked().getType() == EntityType.ARMOR_STAND) {
			
			final Block b = e.getRightClicked().getLocation().add(0, 1.2, 0).getBlock();
			
			for(LuckyBlockType type : LuckyBlockType.values()) {
				
				ArmorStand stand = (ArmorStand) e.getRightClicked();
				if(stand.getCustomName() != null && stand.getCustomName().equalsIgnoreCase(type.name() + ";" + (int)stand.getLocation().getX()
						+ ";" + (int)stand.getLocation().getY() + ";" + (int)stand.getLocation().getZ())) {
					
					if(LBMain.getIsSk89q() && !LBWorldGuard.canBreak(b)) {
						e.setCancelled(true);
						return;
					}
					
					if(LBMain.isBreakPermissions() && !e.getPlayer().hasPermission("luckyblock.break." + type.name().toLowerCase())
							&& !e.getPlayer().hasPermission("luckyblock.break.*")) {
						e.getPlayer().sendMessage(Message.CANT_BREAK_LUCKYBLOCK.getAsString().replace("%lb%",
								type.isLoaded() ? type.get().getCustomName() : type.name()));
						e.setCancelled(true);
						return;
					}
					
					if(type.isLoaded()) {
						if(type.get().tryOpen(b, e.getPlayer(), false)) {
							stand.remove();
							b.setType(Material.AIR);
						}
					} else {
						stand.remove();
						b.setType(Material.AIR);
					}
					e.setCancelled(true);
					
				}
				
			}
			
		}
		
	}
	
	@EventHandler
	public void entity(PlayerInteractEntityEvent e) throws LuckyBlockNotLoadedException {
		
		if(e.getRightClicked().getType() == EntityType.ARMOR_STAND) {
			
			Block b = e.getRightClicked().getLocation().add(0, 1.2, 0).getBlock();
			
			for(LuckyBlockType type : LuckyBlockType.values()) {
				
				if(b.getType() == type.getMaterial()) {
					
					ArmorStand stand = (ArmorStand) e.getRightClicked();
					if(stand.getCustomName().equalsIgnoreCase(type.name() + ";" + (int)stand.getLocation().getX()
							+ ";" + (int)stand.getLocation().getY() + ";" + (int)stand.getLocation().getZ())) {
						
						if(LBMain.isBreakPermissions() && !e.getPlayer().hasPermission("luckyblock.break." + type.name().toLowerCase())
								&& !e.getPlayer().hasPermission("luckyblock.break.*")) {
							e.getPlayer().sendMessage(Message.CANT_BREAK_LUCKYBLOCK.getAsString().replace("%lb%",
									type.isLoaded() ? type.get().getCustomName() : type.name()));
							e.setCancelled(true);
							return;
						}
						
						if(type.isLoaded()) {
							if(type.get().tryOpen(b, e.getPlayer(), false)) {
								stand.remove();
								b.setType(Material.AIR);
							}
						} else {
							stand.remove();
							b.setType(Material.AIR);
						}
						e.setCancelled(true);
						
					}
				
				}
				
			}
			
		}
		
	}
	
}
