name: ntdLuckyBlock
main: me.DenBeKKer.ntdLuckyBlock.LBMain
version: 2.4.2
api-version: 1.13
author: [DenBeKKer]
softdepend: [TokenManager, Vault, WorldEdit, FastAsyncWorldEdit, WorldGuard]
description: Cool revamped LuckyBlock & API. Say goodbye to the sponge and resourcepacks!
website: https://discord.gg/vbYW3sperj

commands:
   ntdluckyblock:
      description: Main plugin command
      usage: /<command> [args]
      aliases: [lb, luckyblock]