package com.github.danirod12.luckyblock.api.model;

import com.github.danirod12.luckyblock.api.LuckyBlockAPI;
import com.github.danirod12.luckyblock.api.util.ColorData;
import lombok.Getter;
import org.bukkit.Material;

import java.util.Objects;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * Class representing a key of a LuckyBlock. It contains all necessary information to create and identify a LuckyBlock.
 */
@Getter
public class LuckyBlockKey {

    private static final Pattern KEY_PATTERN = Pattern.compile("^(?!.*__)([a-zA-Z1-9][a-zA-Z_1-9]{1,30}[a-zA-Z1-9])$");
    private final String key;
    private final LuckyBlockType internal;
    private final ColorData colorData;
    private final Material material;
    private final boolean applyColorDataToBlock;

    /**
     * Creates a new LuckyBlockKey with the provided parameters.
     * The key is case-insensitive and will be converted to lowercase.
     *
     * @param key                      the unique identifier of the LuckyBlock. It should contain only letters,
     *                                 numbers and underscores, but cannot start or end with an underscore.
     *                                 Key length should be from 3 to 32 chars.
     *                                 You cannot use __ in the key. It cannot be "random".
     * @param colorData                the color data of the LuckyBlock. It will be used for the default custom name
     *                                 and can be applied to the block if applyColorDataToBlock is true.
     * @param material                 the material of the LuckyBlock. It must be a solid block.
     * @param applyColorDataToBlock    whether to apply the color data to the block.
     *                                 If true, the block will have a colored texture based on the color data (1.12-).
     * @throws IllegalArgumentException if any of the parameters are invalid.
     */
    public LuckyBlockKey(String key, ColorData colorData, Material material, boolean applyColorDataToBlock) {
        Objects.requireNonNull(key);
        Objects.requireNonNull(colorData);
        Objects.requireNonNull(material);
        if (key.equalsIgnoreCase("random")) {
            throw new IllegalArgumentException("Key cannot be 'random'");
        }
        if (!KEY_PATTERN.matcher(key).matches()) {
            throw new IllegalArgumentException("Incorrect key. Key could contain a-z letters and _, but cannot"
                    + " start or end with _. Key length should be from 3 to 32 chars. You cannot use __");
        }
        if (!material.isSolid()) {
            throw new IllegalArgumentException("Provided material is not solid");
        }
        this.key = key.toLowerCase();
        this.internal = LuckyBlockType.parse(key);
        this.colorData = this instanceof NotLoadedLuckyBlockKey
                && this.internal != null ? this.internal.getColorData() : colorData;
        this.material = material;
        this.applyColorDataToBlock = applyColorDataToBlock;
    }

    /**
     * Gets the default custom name of the LuckyBlock based on its key and color data.
     * The name is generated by capitalizing the first letter of each word in the key and appending " LuckyBlock".
     *
     * @return the default custom name of the LuckyBlock
     */
    public String getDefaultCustomName() {
        StringBuilder builder = new StringBuilder("§" + colorData.asColorCode());
        for (String s : key.split("_")) {
            builder.append(String.valueOf(s.toCharArray()[0]).toUpperCase()).append(s.substring(1));
        }
        return builder.append(" LuckyBlock").toString();
    }

    /**
     * Checks if this LuckyBlockKey represents an internal LuckyBlockType.
     *
     * @return true if this key corresponds to an internal type, false otherwise
     */
    public boolean isInternal() {
        return internal != null;
    }

    /**
     * Gets the LuckyBlock associated with this key from the LuckyBlockAPI.
     *
     * @return an Optional containing the LuckyBlock if it is loaded, or an empty Optional if it is not loaded
     */
    public Optional<LuckyBlock> getSetup() {
        return LuckyBlockAPI.getLuckyEngineProvider().get(this);
    }

    @Override
    public int hashCode() {
        return key.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof LuckyBlockKey) {
            return ((LuckyBlockKey) obj).key.equals(key);
        }
        return false;
    }

    @Override
    public String toString() {
        return key;
    }

    /**
     * A subclass of LuckyBlockKey used to represent keys of LuckyBlocks that are not loaded in the engine.
     * This class is used internally to handle cases where a LuckyBlockKey is referenced but the corresponding
     * LuckyBlock is not available in the engine. It provides default values for colorData and material based on
     * the internal type if it exists, or defaults to white color and glass material
     * if the internal type is not recognized.
     */
    public static class NotLoadedLuckyBlockKey extends LuckyBlockKey {

        public NotLoadedLuckyBlockKey(String key) {
            super(key, ColorData.WHITE, Material.GLASS, false);
        }
    }
}
